name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh & docker
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/jimlyassidqi/projects/belajar-cicd-docker-2
            git pull origin main
            docker build -t belajar-cicd-docker-2 .
            docker stop belajar-cicd-docker-container-2 || true
            docker rm belajar-cicd-docker-container-2 || true
            docker run -d --name belajar-cicd-docker-container-2 --netwok=host belajar-cicd-docker-2
